// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd3P0qibvKM8oQJ303qoHEy-Ejljlkrkg',
    appId: '1:234130676275:web:d7026e4a6bfaaf1900e146',
    messagingSenderId: '234130676275',
    projectId: 'recipx-e23cc',
    authDomain: 'recipx-e23cc.firebaseapp.com',
    storageBucket: 'recipx-e23cc.appspot.com',
    measurementId: 'G-VLDZVZX0QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGmCrvHghu0VJ0s0mP6iNfcp069WkBw8',
    appId: '1:234130676275:android:11e5dab499b1b2bc00e146',
    messagingSenderId: '234130676275',
    projectId: 'recipx-e23cc',
    storageBucket: 'recipx-e23cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd1P08fl9XI0RmOLy2hcbwNafHLBi9HlY',
    appId: '1:234130676275:ios:76b8367ef3107dc900e146',
    messagingSenderId: '234130676275',
    projectId: 'recipx-e23cc',
    storageBucket: 'recipx-e23cc.appspot.com',
    iosBundleId: 'fr.bechamello.recipx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd1P08fl9XI0RmOLy2hcbwNafHLBi9HlY',
    appId: '1:234130676275:ios:5b111fa4dd4fced600e146',
    messagingSenderId: '234130676275',
    projectId: 'recipx-e23cc',
    storageBucket: 'recipx-e23cc.appspot.com',
    iosBundleId: 'fr.bechamello.recipx.RunnerTests',
  );
}
